apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pythonflask-v1
  name: pythonflask-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonflask-v1
  strategy: {}
  template:
    metadata:
      labels:
        app: pythonflask-v1
    spec:
      containers:
      - image: pythonflask:v1
        name: pythonflask-v1
        ports:
        - containerPort: 5000
